/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessPlanRouteImport } from './routes/business-plan'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlanRoute = BusinessPlanRouteImport.update({
  id: '/business-plan',
  path: '/business-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/contact': typeof ContactRoute
  '/financials': typeof FinancialsRoute
  '/fleet': typeof FleetRoute
  '/platform': typeof PlatformRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/contact': typeof ContactRoute
  '/financials': typeof FinancialsRoute
  '/fleet': typeof FleetRoute
  '/platform': typeof PlatformRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/contact': typeof ContactRoute
  '/financials': typeof FinancialsRoute
  '/fleet': typeof FleetRoute
  '/platform': typeof PlatformRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-plan'
    | '/contact'
    | '/financials'
    | '/fleet'
    | '/platform'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-plan'
    | '/contact'
    | '/financials'
    | '/fleet'
    | '/platform'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/business-plan'
    | '/contact'
    | '/financials'
    | '/fleet'
    | '/platform'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessPlanRoute: typeof BusinessPlanRoute
  ContactRoute: typeof ContactRoute
  FinancialsRoute: typeof FinancialsRoute
  FleetRoute: typeof FleetRoute
  PlatformRoute: typeof PlatformRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-plan': {
      id: '/business-plan'
      path: '/business-plan'
      fullPath: '/business-plan'
      preLoaderRoute: typeof BusinessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessPlanRoute: BusinessPlanRoute,
  ContactRoute: ContactRoute,
  FinancialsRoute: FinancialsRoute,
  FleetRoute: FleetRoute,
  PlatformRoute: PlatformRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
