/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UzbekRouteImport } from './routes/uzbek'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as BusinessPlanRouteImport } from './routes/business-plan'
import { Route as IndexRouteImport } from './routes/index'

const UzbekRoute = UzbekRouteImport.update({
  id: '/uzbek',
  path: '/uzbek',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlanRoute = BusinessPlanRouteImport.update({
  id: '/business-plan',
  path: '/business-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/financials': typeof FinancialsRoute
  '/fleet': typeof FleetRoute
  '/platform': typeof PlatformRoute
  '/uzbek': typeof UzbekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/financials': typeof FinancialsRoute
  '/fleet': typeof FleetRoute
  '/platform': typeof PlatformRoute
  '/uzbek': typeof UzbekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/financials': typeof FinancialsRoute
  '/fleet': typeof FleetRoute
  '/platform': typeof PlatformRoute
  '/uzbek': typeof UzbekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-plan'
    | '/financials'
    | '/fleet'
    | '/platform'
    | '/uzbek'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business-plan' | '/financials' | '/fleet' | '/platform' | '/uzbek'
  id:
    | '__root__'
    | '/'
    | '/business-plan'
    | '/financials'
    | '/fleet'
    | '/platform'
    | '/uzbek'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessPlanRoute: typeof BusinessPlanRoute
  FinancialsRoute: typeof FinancialsRoute
  FleetRoute: typeof FleetRoute
  PlatformRoute: typeof PlatformRoute
  UzbekRoute: typeof UzbekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uzbek': {
      id: '/uzbek'
      path: '/uzbek'
      fullPath: '/uzbek'
      preLoaderRoute: typeof UzbekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-plan': {
      id: '/business-plan'
      path: '/business-plan'
      fullPath: '/business-plan'
      preLoaderRoute: typeof BusinessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessPlanRoute: BusinessPlanRoute,
  FinancialsRoute: FinancialsRoute,
  FleetRoute: FleetRoute,
  PlatformRoute: PlatformRoute,
  UzbekRoute: UzbekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
